package View;

import Model.DAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS;
import static javax.swing.JTable.AUTO_RESIZE_OFF;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Murilo
 */
public final class Index extends javax.swing.JFrame {

    /**
     * Creates new form index
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public Index() throws ClassNotFoundException, SQLException {
        initComponents();
        this.atualizaTabelaCliente();
        
    }
    DAO d = new DAO();
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        btnCliente = new javax.swing.JButton();
        btnMunicipio = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        rdCliente = new javax.swing.JRadioButton();
        rdMunicipio = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Ampix");

        Tabela.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabela.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Tabela.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Tabela.setDropMode(javax.swing.DropMode.ON);
        Tabela.setFocusable(false);
        Tabela.setInheritsPopupMenu(true);
        Tabela.setRowHeight(20);
        Tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabela);
        Tabela.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnCliente.setText("Adicionar Cliente");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });

        btnMunicipio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnMunicipio.setText("Adicionar Município");
        btnMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMunicipioActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdCliente);
        rdCliente.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdCliente.setSelected(true);
        rdCliente.setText("Cliente");
        rdCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdClienteFocusGained(evt);
            }
        });
        rdCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdClienteMouseClicked(evt);
            }
        });

        buttonGroup1.add(rdMunicipio);
        rdMunicipio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        rdMunicipio.setText("Município");
        rdMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rdMunicipioFocusGained(evt);
            }
        });
        rdMunicipio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdMunicipioMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Escolha a tabela a ser mostrada:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMunicipio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rdCliente)
                        .addGap(18, 18, 18)
                        .addComponent(rdMunicipio)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rdCliente)
                    .addComponent(rdMunicipio)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMunicipio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPesquisar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMunicipioActionPerformed
        new CadastroMunicipio().setVisible(true);
    }//GEN-LAST:event_btnMunicipioActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
        try {
            new CadastroCliente().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnClienteActionPerformed

    private void rdClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdClienteMouseClicked
        this.atualizaTabelaCliente();
    }//GEN-LAST:event_rdClienteMouseClicked

    private void rdMunicipioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdMunicipioMouseClicked
        //SETA OS DADOS DO BANCO DE DADOS NA TABELA QUANDO O BOTAO RÁDIO FOR CLICADO
        atualizaTabelaMunicipio();
    }//GEN-LAST:event_rdMunicipioMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        if(this.rdCliente.isSelected()){
            this.atualizaTabelaCliente();
        }
        else if(this.rdMunicipio.isSelected()){
            this.atualizaTabelaMunicipio();    
        }
        
        
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        //PEGA A LINHA SELECIONADA
        
        int linha = this.Tabela.getSelectedRow();
        
        //PEGA O VALOR DA LINHA E COLUNA 0 PARA PEGAR O CAMPO CÓDIGO SEMPRE
        String selecionado = (String) this.Tabela.getValueAt(linha, 0);
        
        //SETA A VARIAVEL DA CLASSE DAO O VALOR DE CÓDIGO DA LINHA SELECIONADA
        DAO.campoSelecionado = selecionado;
        
        EditarCliente c;
        EditarMunicipio m;
        
        try {
            if(this.rdCliente.isSelected()){
                c = new EditarCliente();
                c.setVisible(true);
            }
            else if(this.rdMunicipio.isSelected()){
                m = new EditarMunicipio();
                m.setVisible(true);
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        //PEGA A LINHA SELECIONADA NA TABELA E DEPOIS JOGA NA VARIAVEL SELECIONADO
        //O CONTEUDO DA LINHA SELECIONADO NA COLUNA CODIGO
        int linha = this.Tabela.getSelectedRow();
        String selecionado = (String) this.Tabela.getValueAt(linha, 0);
        
        
        int rsp = JOptionPane.showConfirmDialog(null,"Você tem certeza?");
        
        //SE ELE CLICAR EM SIM, ENTÃO EXCLUI O DADO
        if(rsp == 0){
            //SE O BOTAO RADIO CLIENTE ESTIVER ATIVO ELE EXCLUIR DA TABELA CLIENTE
            if(rdCliente.isSelected()){
                
                try {
                    d.excluirDado(selecionado,1);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            //SE NAO EXCLUI DA TABELA MUNICIPIO
            else{
               
                try {
                    d.excluirDado(selecionado,2);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
                }
              
                this.atualizaTabelaMunicipio();
                
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void rdClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdClienteFocusGained
        this.atualizaTabelaCliente();
    }//GEN-LAST:event_rdClienteFocusGained

    private void rdMunicipioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rdMunicipioFocusGained
        this.atualizaTabelaMunicipio();
    }//GEN-LAST:event_rdMunicipioFocusGained

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            DAO.conexao.close();
        } catch (SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        try {
            new Pesquisar().setVisible(true);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Index().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(Index.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable Tabela;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMunicipio;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdCliente;
    private javax.swing.JRadioButton rdMunicipio;
    // End of variables declaration//GEN-END:variables

    public void atualizaTabelaMunicipio() {
        //SETA OS DADOS DO BANCO DE DADOS NA TABELA QUANDO O BOTAO RADIO FOR CLICADO
        try {
            this.Tabela.setModel(new DAO().atualizaTabela(2,null));
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
        //ASSIM AS 3 COLUNAS OCUPAM TODO O ESPAÇO DA TABELA
        Tabela.setAutoResizeMode(AUTO_RESIZE_ALL_COLUMNS);
    }
    
    
    public void atualizaTabelaCliente(){
        //SETA OS DADOS DO BANCO DE DADOS NA TABELA QUANDO O BOTAO RADIO FOR CLICADO
        try {
            this.Tabela.setModel(new DAO().atualizaTabela(1,null));
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
        
        //ASSIM MOSTRA TODAS AS COLUNAS COM SCROLL LATERAL
        Tabela.setAutoResizeMode(AUTO_RESIZE_OFF);
    }
}
